-- INSERT SUFFIX STREETS:

INSERT INTO common.street_suffix (name, abbrv, is_default)
VALUES
    ('Alley', 'Aly', false),
    ('Annex', 'Anx', false),
    ('Arcade', 'Arc', false),
    ('Avenue', 'Av', false),
    ('Bayou', 'Byu', false),
    ('Beach', 'Bch', false),
    ('Bend', 'Bnd', false),
    ('Bluff', 'Blf', false),
    ('Bluffs', 'Blfs', false),
    ('Bottom', 'Btm', false),
    ('Boulevard', 'Blvd', false),
    ('Branch', 'Br', false),
    ('Bridge', 'Brg', false),
    ('Brook', 'Brk', false),
    ('Brooks', 'Brks', false),
    ('Burg', 'Bg', false),
    ('Burgs', 'Bgs', false),
    ('Bypass', 'Byp', false),
    ('Camp', 'Cp', false),
    ('Canyon', 'Cnyn', false),
    ('Cape', 'Cpe', false),
    ('Causeway', 'Cswy', false),
    ('Center', 'Cen', false),
    ('Centers', 'Ctrs', false),
    ('Circle', 'Cir', false),
    ('Circles', 'Cirs', false),
    ('Cliff', 'Clf', false),
    ('Cliffs', 'Clfs', false),
    ('Club', 'Clb', false),
    ('Common', 'Cmn', false),
    ('Commons', 'Cmns', false),
    ('Corner', 'Cor', false),
    ('Corners', 'Cors', false),
    ('Course', 'Crse', false),
    ('Court', 'Ct', false),
    ('Courts', 'Cts', false),
    ('Cove', 'Cv', false),
    ('Coves', 'Cvs', false),
    ('Creek', 'Crk', false),
    ('Crescent', 'Cres', false),
    ('Crest', 'Crst', false),
    ('Crossing', 'Xing', false),
    ('Crossroad', 'Xrd', false),
    ('Curve', 'Curv', false),
    ('Dale', 'Dl', false),
    ('Dam', 'Dm', false),
    ('Divide', 'Div', false),
    ('Drive', 'Dr', false),
    ('Drives', 'Drs', false),
    ('Estate', 'Est', false),
    ('Estates', 'Ests', false),
    ('Expressway', 'Exp', false),
    ('Extension', 'Ext', false),
    ('Extensions', 'Exts', false),
    ('Fall', '', false),
    ('Falls', 'Fls', false),
    ('Ferry', 'Fry', false),
    ('Field', 'Fld', false),
    ('Fields', 'Flds', false),
    ('Flat', 'Flt', false),
    ('Flats', 'Flts', false),
    ('Ford', 'Frd', false),
    ('Fords', 'Frds', false),
    ('Forest', 'Frst', false),
    ('Forge', 'Frg', false),
    ('Forges', 'Frgs', false),
    ('Fork', 'Frk', false),
    ('Forks', 'Frks', false),
    ('Fort', 'Ft', false),
    ('Freeway', 'Fwy', false),
    ('Garden', 'Gdn', false),
    ('Gardens', 'Gdns', false),
    ('Gateway', 'Gtwy', false),
    ('Glen', 'Gln', false),
    ('Glens', 'Glns', false),
    ('Green', 'Grn', false),
    ('Greens', 'Grns', false),
    ('Grove', 'Grv', false),
    ('Groves', 'Grvs', false),
    ('Harbor', 'Hbr', false),
    ('Harbors', 'Hbrs', false),
    ('Haven', 'Hvn', false),
    ('Heights', 'Hts', false),
    ('Highway', 'Hwy', false),
    ('Hill', 'Hl', false),
    ('Hills', 'Hls', false),
    ('Hollow', 'Holw', false),
    ('Inlet', 'Inlt', false),
    ('Island', 'Is', false),
    ('Islands', 'Iss', false),
    ('Isle', '', false),
    ('Junction', 'Jct', false),
    ('Junctions', 'Jcts', false),
    ('Key', 'Ky', false),
    ('Keys', 'Kys', false),
    ('Knoll', 'Knl', false),
    ('Knolls', 'Knls', false),
    ('Lake', 'Lk', false),
    ('Lakes', 'Lks', false),
    ('Land', '', false),
    ('Landing', 'Lndg', false),
    ('Lane', 'Ln', false),
    ('Light', 'Lgt', false),
    ('Lights', 'Lgts', false),
    ('Loaf', 'Lf', false),
    ('Lock', 'Lck', false),
    ('Locks', 'Lcks', false),
    ('Lodge', 'Ldg', false),
    ('Loop', 'Lp', false),
    ('Mall', '', false),
    ('Manor', 'Mnr', false),
    ('Manors', 'Mnrs', false),
    ('Meadow', 'Mdw', false),
    ('Meadows', 'Mdws', false),
    ('Mews', '', false),
    ('Mill', 'Ml', false),
    ('Mills', 'Mls', false),
    ('Mission', 'Msn', false),
    ('Motorway', 'Mtwy', false),
    ('Mount', 'Mt', false),
    ('Mountain', 'Mtn', false),
    ('Mountains', 'Mtns', false),
    ('Neck', 'Nck', false),
    ('Orchard', 'Orch', false),
    ('Oval', 'Ovl', false),
    ('Overpass', 'Opas', false),
    ('Park', 'Prk', false),
    ('Parks', 'Park', false),
    ('Parkway', 'Pky', false),
    ('Parkways', 'Pkwys', false),
    ('Pass', '', false),
    ('Passage', 'Psge', false),
    ('Path', '', false),
    ('Pike', 'Pk', false),
    ('Pine', 'Pne', false),
    ('Pines', 'Pnes', false),
    ('Place', 'Pl', false),
    ('Plain', 'Pln', false),
    ('Plains', 'Plns', false),
    ('Plaza', 'Plz', false),
    ('Point', 'Pt', false),
    ('Points', 'Pts', false),
    ('Port', 'Prt', false),
    ('Ports', 'Prts', false),
    ('Prairie', 'Pr', false),
    ('Radial', 'Rad', false),
    ('Ramp', '', false),
    ('Ranch', 'Rnch', false),
    ('Rapid', 'Rpd', false),
    ('Rapids', 'Rpds', false),
    ('Rest', 'Rst', false),
    ('Ridge', 'Rdg', false),
    ('Ridges', 'Rdgs', false),
    ('River', 'Riv', false),
    ('Road', 'Rd', false),
    ('Roads', 'Rds', false),
    ('Route', 'Rte', false),
    ('Row', '', false),
    ('Rue', '', false),
    ('Run', '', false),
    ('Shoal', 'Shl', false),
    ('Shoals', 'Shls', false),
    ('Shore', 'Shr', false),
    ('Shores', 'Shrs', false),
    ('Skyway', 'Skwy', false),
    ('Spring', 'Spg', false),
    ('Springs', 'Spgs', false),
    ('Spur', '', false),
    ('Square', 'Sq', false),
    ('Squares', 'Sqs', false),
    ('Station', 'Stn', false),
    ('Strasse', '', false),
    ('Stravenue', 'Stra', false),
    ('Stream', 'Strm', false),
    ('Street', 'St', true),
    ('Streets', 'Sts', false),
    ('Summit', 'Smt', false),
    ('Terrace', 'Terr', false),
    ('Throughway', 'Trwy', false),
    ('Trace', 'Trce', false),
    ('Track', 'Trk', false),
    ('Trafficway', 'Trfy', false),
    ('Trail', 'Trl', false),
    ('Trailer', 'Trlr', false),
    ('Tunnel', 'Tunl', false),
    ('Turnpike', 'Tpke', false),
    ('Underpass', 'Upas', false),
    ('Union', 'Un', false),
    ('Unions', 'Uns', false),
    ('Valley', 'Vly', false),
    ('Valleys', 'Vlys', false),
    ('Via', '', false),
    ('Viaduct', 'Vdct', false),
    ('View', 'Vw', false),
    ('Views', 'Vws', false),
    ('Village', 'Vlg', false),
    ('Villages', 'Vlgs', false),
    ('Ville', 'Vl', false),
    ('Vista', 'Vis', false),
    ('Walk', '', false),
    ('Wall', '', false),
    ('Way', 'Wy', false),
    ('Well', 'Wl', false),
    ('Wells', 'Wls', false);

INSERT INTO common.country (name, iso_code2, iso_code3, is_default)
VALUES
  ('Albania', 'AL', 'ALB', false),
  ('Andorra', 'AD', 'AND', false),
  ('Austria', 'AT', 'AUT', false),
  ('Belarus', 'BY', 'BLR', false),
  ('Belgium', 'BE', 'BEL', false),
  ('Bulgaria', 'BG', 'BGR', false),
  ('Croatia', 'HR', 'HRV', false),
  ('Cyprus', 'CY', 'CYP', false),
  ('Czech Republic', 'CZ', 'CZE', false),
  ('Denmark', 'DK', 'DNK', false),
  ('Estonia', 'EE', 'EST', false),
  ('Finland', 'FI', 'FIN', false),
  ('France', 'FR', 'FRA', false),
  ('Germany', 'DE', 'DEU', false),
  ('Greece', 'GR', 'GRC', false),
  ('Hungary', 'HU', 'HUN', false),
  ('Iceland', 'IS', 'ISL', false),
  ('Ireland', 'IE', 'IRL', false),
  ('Italy', 'IT', 'ITA', false),
  ('Latvia', 'LV', 'LVA', false),
  ('Liechtenstein', 'LI', 'LIE', false),
  ('Lithuania', 'LT', 'LTU', false),
  ('Luxembourg', 'LU', 'LUX', false),
  ('Malta', 'MT', 'MLT', false),
  ('Moldova', 'MD', 'MDA', false),
  ('Monaco', 'MC', 'MCO', false),
  ('Montenegro', 'ME', 'MNE', false),
  ('Netherlands', 'NL', 'NLD', false),
  ('North Macedonia', 'MK', 'MKD', false),
  ('Norway', 'NO', 'NOR', false),
  ('Poland', 'PL', 'POL', false),
  ('Portugal', 'PT', 'PRT', false),
  ('Romania', 'RO', 'ROU', false),
  ('Russia', 'RU', 'RUS', false),
  ('San Marino', 'SM', 'SMR', false),
  ('Serbia', 'RS', 'SRB', false),
  ('Slovakia', 'SK', 'SVK', false),
  ('Slovenia', 'SI', 'SVN', false),
  ('Spain', 'ES', 'ESP', false),
  ('Sweden', 'SE', 'SWE', false),
  ('Switzerland', 'CH', 'CHE', false),
  ('Ukraine', 'UA', 'UKR', false),
  ('United Kingdom', 'GB', 'GBR', false),
  ('United States', 'US', 'USA', true),
  ('Canada', 'CA', 'CAN', false);

-- Insert the top 10 most spoken languages, with English as the default language
INSERT INTO common.language (name, iso_code2, iso_code3, is_default)
VALUES
    ('Mandarin Chinese', 'zh', 'zho', false),
    ('Spanish', 'es', 'spa', false),
    ('English', 'en', 'eng', true), -- English is the default language
    ('Hindi', 'hi', 'hin', false),
    ('Arabic', 'ar', 'ara', false),
    ('Bengali', 'bn', 'ben', false),
    ('Portuguese', 'pt', 'por', false),
    ('Russian', 'ru', 'rus', false),
    ('Japanese', 'ja', 'jpn', false),
    ('Punjabi', 'pa', 'pan', false);

INSERT INTO common.gender (name, is_default)
VALUES
    ('Male', false),
    ('Female', false),
    ('Neuter', true); -- Neuter is the default gender

INSERT INTO common.identity_document_type (name, is_default)
VALUES
    ('Passport', true),
    ('Driver''s License', false),
    ('Social Security Card', false),
    ('Birth Certificate', false),
    ('Marriage Certificate', false),
    ('Green Card', false),
    ('Naturalization Certificate', false),
    ('Visa', false),
    ('State ID Card', false),
    ('Vehicle Registration', false),
    ('Concealed Carry Permit', false),
    ('Professional License', false),
    ('Academic Transcript', false),
    ('Financial Document', false);
