import {Component, OnInit} from '@angular/core';
import {FormControl, FormGroup, ReactiveFormsModule, Validators} from '@angular/forms';
import {AocFormGroupType} from '@atlantis-of-code/aoc-client/core/types';
import {Customer} from '../../../../models/customers/customer';
import {AocRestOptions} from '@atlantis-of-code/aoc-client/aoc-common';
import {CustomerModelConfig} from '../../../../model-configs/customers/customer-model-config';
import {AocFormController, AocFormModule} from '@atlantis-of-code/aoc-client/components/aoc-form';
import {AocUiFormModule} from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-form';
import {AocUiInputTextModule} from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-input-text';
import {QuestDefaultsService} from '../../../../services/quest-defaults-service';
import {AocUiDatetimePickerModule} from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-datetime-picker';
import {GenderAutocompleteComponent} from '../../common/gender/gender-autocomplete.component';
import {LanguageAutocompleteComponent} from '../../common/language/language-autocomplete.component';
import {QuestUtilsService} from '../../../../services/quest-utils.service';
import {LegalDataTemplate} from '../../../../models/templates/legal-data-template';
import {
  LegalDataTemplateSubformComponent
} from '../../templates/legal-data-template/legal-data-template-subform.component';

@Component({
  selector: 'app-customer-form',
  standalone: true,
  providers: [ AocFormController ],
  imports: [
    AocFormModule,
    ReactiveFormsModule,
    AocUiFormModule,
    AocUiInputTextModule,
    AocUiDatetimePickerModule,
    GenderAutocompleteComponent,
    LanguageAutocompleteComponent,
    LegalDataTemplateSubformComponent
  ],
  template: `
    <aoc-form [modelConfig]="modelConfig" [formGroup]="formGroup" [restOptions]="restOptions">
      <ng-template aocFormTemplate="body">
        <aoc-ui-form-page>
          <aoc-ui-form-row>
            <input aocUiInputText aocUiFormField="Code" [formControlName]="CustomerClass.field.CODE" placeholder="Autogenerated on server if empty...">
            <app-language-autocomplete aocUiFormField="Language" [formControlName]="CustomerClass.entity.LANGUAGE"></app-language-autocomplete>
            <app-gender-autocomplete aocUiFormField="Gender" [formControlName]="CustomerClass.entity.GENDER"></app-gender-autocomplete>
          </aoc-ui-form-row>
          <app-legal-data-template-subform [formGroupName]="CustomerClass.embedded.LEGAL_DATA_TEMPLATE"></app-legal-data-template-subform>
          <aoc-ui-form-row>
            <input aocUiInputText aocUiFormField="Trade name" [span]="18" [formControlName]="CustomerClass.field.TRADE_NAME" placeholder="Just for companies, not mandatory...">
            <aoc-ui-datetime-picker aocUiFormField="Birthdate" [formControlName]="CustomerClass.field.BIRTHDATE" mode="date"></aoc-ui-datetime-picker>
          </aoc-ui-form-row>
        </aoc-ui-form-page>
      </ng-template>
    </aoc-form>
  `
})
export default class CustomerFormComponent implements OnInit {
  protected CustomerClass = Customer;

  protected formGroup: FormGroup<AocFormGroupType<Customer>>;

  protected restOptions: AocRestOptions<Customer>;

  constructor(
    protected modelConfig: CustomerModelConfig,
    private questDefaultsService: QuestDefaultsService,
    private questUtilsService: QuestUtilsService,
    private formController: AocFormController<Customer>
  ) {}

  ngOnInit() {
    this.formGroup = new FormGroup<AocFormGroupType<Customer>>({
      code: new FormControl(null),
      trade_name: new FormControl(null),
      birthdate: new FormControl(null),
      gender: new FormControl(this.questDefaultsService.gender),
      language: new FormControl(this.questDefaultsService.language, Validators.required),
      legalDataTemplate: this.questUtilsService.addControlsForLegalDataTemplate(new FormGroup({})),
    });

    this.formController.addBeforeSaveAction(action => {
      console.log(action.model);
      return 'PEEEERA';
    })
  }

  protected readonly Customer = Customer;
}
