import { Component, inject, OnInit } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { AocRestOptions } from '@atlantis-of-code/aoc-client/aoc-common';
import { AocFormController, AocFormModule } from '@atlantis-of-code/aoc-client/components/aoc-form';
import { AocFormGroupType } from '@atlantis-of-code/aoc-client/core/types';
import { AocUiValidators } from '@atlantis-of-code/aoc-client/ui/common/validators';
import { AocUiCkeditorModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-ck-editor';
import { AocUiFormModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-form';
import { AocUiInputCheckboxModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-input-checkbox';
import { AocUiInputTextModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-input-text';
import {
  AocUiWindowDynConfig,
  AocUiWindowDynConfigurable
} from '@atlantis-of-code/aoc-client/ui/overlay/aoc-ui-window';
import { AocUiTabPanelModule } from '@atlantis-of-code/aoc-client/ui/panel/aoc-ui-tab-panel';
import { ItemModelConfig } from '../../../../model-configs/items/item-model-config';
import { Item } from '../../../../models/items/item';
import { QuestDefaultsService } from '../../../../services/quest-defaults-service';
import { TaxAutocompleteComponent } from '../../common/tax/tax-autocomplete.component';
import { FileGridFieldComponent } from '../../files/file-grid-field.component';
import { FilePhotoFieldComponent } from '../../files/file-photo-field.component';
import { CategoryAutocompleteComponent } from '../category/category-autocomplete.component';

@Component({
  selector: 'app-item-form',
  standalone: true,
  providers: [AocFormController],
  imports: [
    AocFormModule,
    ReactiveFormsModule,
    AocUiFormModule,
    AocUiInputTextModule,
    AocUiInputCheckboxModule,
    TaxAutocompleteComponent,
    CategoryAutocompleteComponent,
    FilePhotoFieldComponent,
    AocUiTabPanelModule,
    FileGridFieldComponent,
    AocUiCkeditorModule
  ],
  template: `
    <aoc-form [formGroup]="formGroup" [modelConfig]="modelConfig" [restOptions]="restOptions">
      <ng-template aocFormTemplate="body">
        <aoc-ui-tab-panel>
          <aoc-ui-tab-panel-content header="Data">
            <aoc-ui-form-page>
              <aoc-ui-form-row>
                <input type="checkbox" aocUiInputCheckbox aocUiFormField="Enabled"
                       [formControlName]="$.field.IS_ENABLED" [span]="3">
                <input aocUiInputText aocUiFormField="Code" [formControlName]="$.field.CODE"
                       placeholder="Autogenerated on server if empty..." [span]="7">
                <input aocUiInputText aocUiFormField="Name" [formControlName]="$.field.NAME">
              </aoc-ui-form-row>
              <aoc-ui-form-row>
                <input aocUiInputText aocUiFormField="Base price" [formControlName]="$.field.BASE_PRICE">
                <app-tax-autocomplete aocUiFormField="Tax" [formControlName]="$.entity.TAX"
                                      allow="none"></app-tax-autocomplete>
                <app-category-autocomplete aocUiFormField="Category" [formControlName]="$.entity.CATEGORY"
                                           allow="none"></app-category-autocomplete>
              </aoc-ui-form-row>
              <aoc-ui-form-row aocUiFormRowHeight="stretch">
                <app-file-photo-field
                  aocUiFormField="Photo"
                  [formControlName]="$.entity.PHOTO"
                  fileDirectory="Items"
                  fileSubdirectory="Photos"
                  [fileParentClass]="$"
                ></app-file-photo-field>
              </aoc-ui-form-row>
            </aoc-ui-form-page>
          </aoc-ui-tab-panel-content>
          <aoc-ui-tab-panel-content header="Description">
            <aoc-ui-form-page>
              <aoc-ui-form-row aocUiFormRowHeight="stretch">
                <aoc-ui-ckeditor aocUiFormField="Detailed description"
                                 [formControlName]="$.field.DESCRIPTION"></aoc-ui-ckeditor>
              </aoc-ui-form-row>
            </aoc-ui-form-page>
          </aoc-ui-tab-panel-content>
          <aoc-ui-tab-panel-content header="Files">
            <aoc-ui-form-page>
              <aoc-ui-form-row aocUiFormRowHeight="stretch">
                <app-file-grid-field
                  aocUiFormField="Files"
                  [formControlName]="$.collection.FILE"
                  fileDirectory="Items"
                  fileSubdirectory="Extra"
                  [fileParentClass]="$"
                ></app-file-grid-field>
              </aoc-ui-form-row>
            </aoc-ui-form-page>
          </aoc-ui-tab-panel-content>
        </aoc-ui-tab-panel>
      </ng-template>
    </aoc-form>
  `
})
export default class ItemFormComponent implements OnInit, AocUiWindowDynConfigurable {
  protected $ = Item;
  protected modelConfig = inject(ItemModelConfig);
  protected formGroup: FormGroup<AocFormGroupType<Item>>;
  protected restOptions: AocRestOptions<Item> = {
    populate: {
      tax: true,
      category: true,
      photo: true,
      fileCollection: true
    }
  };

  private questDefaultsService = inject(QuestDefaultsService);

  ngOnInit() {
    this.formGroup = new FormGroup<AocFormGroupType<Item>>({
      is_enabled: new FormControl(true, Validators.required),
      code: new FormControl(null, AocUiValidators.positiveNumber(0)),
      name: new FormControl(null, Validators.required),
      description: new FormControl(null),
      base_price: new FormControl('0', [Validators.required, AocUiValidators.positiveNumber(2)]),
      tax: new FormControl(this.questDefaultsService.$tax, Validators.required),
      category: new FormControl(null),
      photo: new FormControl(null),
      fileCollection: new FormControl([])
    });
  }

  createAocUiWindowDynConfig(): AocUiWindowDynConfig {
    return {
      width: 800,
      height: 640
    };
  }
}
