CREATE SCHEMA common;

CREATE TABLE common.country (
    id bigserial primary key ,
    name text not null,
    iso_code2 text,
    iso_code3 text,
    is_default boolean not null default false -- overridden by customer default
) INHERITS (public.meta);

CREATE TABLE common.street_suffix (
    id bigserial primary key ,
    name text not null,
    abbrv text,
    is_default boolean not null default false
) INHERITS (public.meta);

CREATE TABLE common.identity_document_type (
    id bigserial primary key ,
    name text not null,
    is_default boolean not null default false
) INHERITS (public.meta);

CREATE TABLE common.payment_system ( -- payment_system
    id bigserial primary key ,
    name text not null,
    is_default boolean not null default false
) inherits (public.meta);

CREATE TABLE common.fiscal_year (
    id bigserial primary key ,
    year integer not null ,
    is_current boolean default false
) inherits (public.meta);

CREATE TABLE common.language (
    id bigserial primary key ,
    name text not null,
    iso_code2 text,
    iso_code3 text,
    is_default boolean not null default false
) inherits (public.meta);

CREATE TABLE common.gender (
    id bigserial primary key ,
    name text not null,
    is_default boolean not null default false
) inherits (public.meta);

CREATE TABLE common.tax (
    id bigserial primary key ,
    name text not null,
    percent numeric not null -- rate
) inherits (public.meta);

CREATE TABLE common.series (
    id bigserial primary key ,
    name text not null unique ,
    type text not null check (type in ('Invoice', 'Delivery note', 'Budget', 'Ticket'))
) inherits (public.meta);

-- INSERT SUFFIX STREETS:

INSERT INTO common.street_suffix (name, abbrv)
VALUES
    ('Alley', 'Aly'),
    ('Annex', 'Anx'),
    ('Arcade', 'Arc'),
    ('Avenue', 'Av'),
    ('Bayou', 'Byu'),
    ('Beach', 'Bch'),
    ('Bend', 'Bnd'),
    ('Bluff', 'Blf'),
    ('Bluffs', 'Blfs'),
    ('Bottom', 'Btm'),
    ('Boulevard', 'Blvd'),
    ('Branch', 'Br'),
    ('Bridge', 'Brg'),
    ('Brook', 'Brk'),
    ('Brooks', 'Brks'),
    ('Burg', 'Bg'),
    ('Burgs', 'Bgs'),
    ('Bypass', 'Byp'),
    ('Camp', 'Cp'),
    ('Canyon', 'Cnyn'),
    ('Cape', 'Cpe'),
    ('Causeway', 'Cswy'),
    ('Center', 'Cen'),
    ('Centers', 'Ctrs'),
    ('Circle', 'Cir'),
    ('Circles', 'Cirs'),
    ('Cliff', 'Clf'),
    ('Cliffs', 'Clfs'),
    ('Club', 'Clb'),
    ('Common', 'Cmn'),
    ('Commons', 'Cmns'),
    ('Corner', 'Cor'),
    ('Corners', 'Cors'),
    ('Course', 'Crse'),
    ('Court', 'Ct'),
    ('Courts', 'Cts'),
    ('Cove', 'Cv'),
    ('Coves', 'Cvs'),
    ('Creek', 'Crk'),
    ('Crescent', 'Cres'),
    ('Crest', 'Crst'),
    ('Crossing', 'Xing'),
    ('Crossroad', 'Xrd'),
    ('Curve', 'Curv'),
    ('Dale', 'Dl'),
    ('Dam', 'Dm'),
    ('Divide', 'Div'),
    ('Drive', 'Dr'),
    ('Drives', 'Drs'),
    ('Estate', 'Est'),
    ('Estates', 'Ests'),
    ('Expressway', 'Exp'),
    ('Extension', 'Ext'),
    ('Extensions', 'Exts'),
    ('Fall', ''),
    ('Falls', 'Fls'),
    ('Ferry', 'Fry'),
    ('Field', 'Fld'),
    ('Fields', 'Flds'),
    ('Flat', 'Flt'),
    ('Flats', 'Flts'),
    ('Ford', 'Frd'),
    ('Fords', 'Frds'),
    ('Forest', 'Frst'),
    ('Forge', 'Frg'),
    ('Forges', 'Frgs'),
    ('Fork', 'Frk'),
    ('Forks', 'Frks'),
    ('Fort', 'Ft'),
    ('Freeway', 'Fwy'),
    ('Garden', 'Gdn'),
    ('Gardens', 'Gdns'),
    ('Gateway', 'Gtwy'),
    ('Glen', 'Gln'),
    ('Glens', 'Glns'),
    ('Green', 'Grn'),
    ('Greens', 'Grns'),
    ('Grove', 'Grv'),
    ('Groves', 'Grvs'),
    ('Harbor', 'Hbr'),
    ('Harbors', 'Hbrs'),
    ('Haven', 'Hvn'),
    ('Heights', 'Hts'),
    ('Highway', 'Hwy'),
    ('Hill', 'Hl'),
    ('Hills', 'Hls'),
    ('Hollow', 'Holw'),
    ('Inlet', 'Inlt'),
    ('Island', 'Is'),
    ('Islands', 'Iss'),
    ('Isle', ''),
    ('Junction', 'Jct'),
    ('Junctions', 'Jcts'),
    ('Key', 'Ky'),
    ('Keys', 'Kys'),
    ('Knoll', 'Knl'),
    ('Knolls', 'Knls'),
    ('Lake', 'Lk'),
    ('Lakes', 'Lks'),
    ('Land', ''),
    ('Landing', 'Lndg'),
    ('Lane', 'Ln'),
    ('Light', 'Lgt'),
    ('Lights', 'Lgts'),
    ('Loaf', 'Lf'),
    ('Lock', 'Lck'),
    ('Locks', 'Lcks'),
    ('Lodge', 'Ldg'),
    ('Loop', 'Lp'),
    ('Mall', ''),
    ('Manor', 'Mnr'),
    ('Manors', 'Mnrs'),
    ('Meadow', 'Mdw'),
    ('Meadows', 'Mdws'),
    ('Mews', ''),
    ('Mill', 'Ml'),
    ('Mills', 'Mls'),
    ('Mission', 'Msn'),
    ('Motorway', 'Mtwy'),
    ('Mount', 'Mt'),
    ('Mountain', 'Mtn'),
    ('Mountains', 'Mtns'),
    ('Neck', 'Nck'),
    ('Orchard', 'Orch'),
    ('Oval', 'Ovl'),
    ('Overpass', 'Opas'),
    ('Park', 'Prk'),
    ('Parks', 'Park'),
    ('Parkway', 'Pky'),
    ('Parkways', 'Pkwys'),
    ('Pass', ''),
    ('Passage', 'Psge'),
    ('Path', ''),
    ('Pike', 'Pk'),
    ('Pine', 'Pne'),
    ('Pines', 'Pnes'),
    ('Place', 'Pl'),
    ('Plain', 'Pln'),
    ('Plains', 'Plns'),
    ('Plaza', 'Plz'),
    ('Point', 'Pt'),
    ('Points', 'Pts'),
    ('Port', 'Prt'),
    ('Ports', 'Prts'),
    ('Prairie', 'Pr'),
    ('Radial', 'Rad'),
    ('Ramp', ''),
    ('Ranch', 'Rnch'),
    ('Rapid', 'Rpd'),
    ('Rapids', 'Rpds'),
    ('Rest', 'Rst'),
    ('Ridge', 'Rdg'),
    ('Ridges', 'Rdgs'),
    ('River', 'Riv'),
    ('Road', 'Rd'),
    ('Roads', 'Rds'),
    ('Route', 'Rte'),
    ('Row', ''),
    ('Rue', ''),
    ('Run', ''),
    ('Shoal', 'Shl'),
    ('Shoals', 'Shls'),
    ('Shore', 'Shr'),
    ('Shores', 'Shrs'),
    ('Skyway', 'Skwy'),
    ('Spring', 'Spg'),
    ('Springs', 'Spgs'),
    ('Spur', ''),
    ('Square', 'Sq'),
    ('Squares', 'Sqs'),
    ('Station', 'Stn'),
    ('Strasse', ''),
    ('Stravenue', 'Stra'),
    ('Stream', 'Strm'),
    ('Street', 'St', true),
    ('Streets', 'Sts'),
    ('Summit', 'Smt'),
    ('Terrace', 'Terr'),
    ('Throughway', 'Trwy'),
    ('Trace', 'Trce'),
    ('Track', 'Trk'),
    ('Trafficway', 'Trfy'),
    ('Trail', 'Trl'),
    ('Trailer', 'Trlr'),
    ('Tunnel', 'Tunl'),
    ('Turnpike', 'Tpke'),
    ('Underpass', 'Upas'),
    ('Union', 'Un'),
    ('Unions', 'Uns'),
    ('Valley', 'Vly'),
    ('Valleys', 'Vlys'),
    ('Via', ''),
    ('Viaduct', 'Vdct'),
    ('View', 'Vw'),
    ('Views', 'Vws'),
    ('Village', 'Vlg'),
    ('Villages', 'Vlgs'),
    ('Ville', 'Vl'),
    ('Vista', 'Vis'),
    ('Walk', ''),
    ('Wall', ''),
    ('Way', 'Wy'),
    ('Well', 'Wl'),
    ('Wells', 'Wls');
