name: quest
services:
  postgresql:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initial-structure/.:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@dev.dev
      - PGADMIN_DEFAULT_PASSWORD=dev
    depends_on:
      - postgresql
volumes:
  postgres:
  pgadmin:
