import { Component, Input } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { AocFormModule } from '@atlantis-of-code/aoc-client/components/aoc-form';
import { AocUiDatetimePickerModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-datetime-picker';
import { AocUiFormModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-form';
import { AocUiInputTextModule } from '@atlantis-of-code/aoc-client/ui/form/aoc-ui-input-text';
import { SeriesType } from '../../../../models/common/series';
import { DocumentTemplate } from '../../../../models/templates/document-template';
import { FiscalYearAutocompleteComponent } from '../../common/fiscal-year/fiscal-year-autocomplete.component';
import { SeriesAutocomplete } from '../../common/series/series-autocomplete';
import { CustomerAutocompleteComponent } from '../../customers/customer/customer-autocomplete.component';

@Component({
  selector: 'app-document-template-subform',
  standalone: true,
  imports: [
    AocFormModule,
    ReactiveFormsModule,
    AocUiFormModule,
    FiscalYearAutocompleteComponent,
    SeriesAutocomplete,
    AocUiInputTextModule,
    CustomerAutocompleteComponent,
    AocUiDatetimePickerModule
  ],
  template: `
    <aoc-subform>
        <ng-template let-formGroup>
          <ng-container [formGroup]="formGroup">
            <aoc-ui-form-row>
              <div aocUiFormRowElement [span]="2" style="font-weight: bold; display: flex; align-items: center">{{this.seriesType?.toUpperCase()}}</div>
              <app-fiscal-year-autocomplete [span]="3" aocUiFormField="Fiscal Year" [formControlName]="$.entity.FISCAL_YEAR" allow="none"></app-fiscal-year-autocomplete>
              <aoc-ui-datetime-picker [span]="4" aocUiFormField="Date" [formControlName]="$.field.DATE" placeholder="Autogenerated on server..."></aoc-ui-datetime-picker>
              <app-series-autocomplete [span]="4" aocUiFormField="Series" [type]="seriesType" [formControlName]="$.entity.SERIES" allow="none"></app-series-autocomplete>
              <input aocUiInputText [span]="3" aocUiFormField="Number" [formControlName]="$.field.NUMBER" placeholder="Autogenerated on server...">
              <app-customer-autocomplete aocUiFormField="Customer" [formControlName]="$.entity.CUSTOMER"></app-customer-autocomplete>
            </aoc-ui-form-row>
            <aoc-ui-form-row>
              <input aocUiInputText aocUiFormField="Observations" [formControlName]="$.field.OBSERVATIONS">
            </aoc-ui-form-row>
          </ng-container>
        </ng-template>
    </aoc-subform>
  `
})
export class DocumentTemplateSubformComponent {
  @Input() seriesType: SeriesType;
  protected $ = DocumentTemplate;
}
